export { default as HomePage } from './home/home';
export { default as ProfilePage } from './profile/profile';
export { default as TasksPage } from './tasks/tasks';
export { default as ClientsPage } from './clients/clients';
export { default as FormsPage } from './forms/forms';
export { default as RegionsPage } from './regions/regions';
export { default as BanckAccountPage } from './bankAccount/bankAccount';
export { default as EstablishmentPage} from './establishment/establishment';
export { default as ReportPage} from './reports/reports';
export { default as Gallery} from './gallery/gallery';
export { default as EditForm} from './forms/editForm/editForm';
export { default as EstablishmentNew } from './EstablishmentNew/EstablishmentNew';
export { default as AssigmentClients } from './AssigmentClients/AssigmentClients';
export { default as Activation } from './Activation/Activation';
